export const el = {
  btnGotoBoot:   document.getElementById('btnGotoBoot'),
  btnFactorySet: document.getElementById('btnFactorySet'),
  btnSystemReset:document.getElementById('btnSystemReset'),
  btnDownload:   document.getElementById('btnDownload'),
  btnGetNetwork: document.getElementById('btnGetNetwork'),
  btnSetNetwork: document.getElementById('btnSetNetwork'),
  appConfirmed:  document.getElementById('appConfirmed'),
  rtcTime:       document.getElementById('RtcTime'),
  ip:            document.getElementById('ip'),
  subnet:        document.getElementById('subnet'),
  gateway:       document.getElementById('gateway'),
  logBox:        document.getElementById('logBox'),
  modelName:     document.getElementById('modelName'),
  btnFsList:     document.getElementById('btnFsList'),
  btnFsDownload: document.getElementById('btnFsDownload'),
  btnFsDelete:   document.getElementById('btnFsDelete'),
  btnFsClose:    document.getElementById('btnFsClose'),
  btnFsUpload:   document.getElementById('btnFsUpload'),
  fsUploadInput: document.getElementById('fsUploadInput'),
  fsBreadcrumb:  document.getElementById('fsBreadcrumb'),
  fsFileList:    document.getElementById('fsFileList'),
  fsEditor:      document.getElementById('fsEditor'),
  fsFileName:    document.getElementById('fsFileName')
};
